### ISSUE TITLE
Trakt Rater dialog is not scaling correctly (controls are hidden at bottom)

### ISSUE THREAD

**Issue by Morb1us** [damienhaynes/TraktRater#82] opened 2018-01-17 19:19 UTC
<s>Hi, I have a problem with the TraktRater. When I click to authorize Trakt.tv, open the browser and show me the pin. I enter it, but the page from the browser shows me the PIN all the time. I authorized KODI on Trakt.tv and I know that the site should be closed. 
In the field where the pin is entered, no button is shown and I can edit the field with the pin all the time. 

In the "options" tab, when I click on maintenance, it becomes gray for a moment, the main window shows a message that I can delete the token so I am logged in but there is no "import" button. The only thing I can do is clear the rating of films that were added on trakt.tv. I can do this from maintenance bookmark.</s>
I already know what the problem is, the program window is as if cut off and does not show the full content. I solved the problem by installing the old version and using Tab moved to the Import option.
Why the window does not show the full content, .NetFramework I have in the latest available version
Pls, help me
Sorry my english is slightly poor

**Comment by damienhaynes** [comment] 2018-01-18 00:51
Could you provide a screenshot?

**Comment by Morb1us** [comment] 2018-01-18 15:47
![zxc](https://user-images.githubusercontent.com/35540595/35106727-44a0fd22-fc6f-11e7-8794-2f837e759c39.jpg)

**Comment by damienhaynes** [comment] 2018-01-19 01:11
That's very odd! 

I don't understand why you can see everything in the older version and not in this version. Can you play around with your font settings in windows, see if 100% fixes the problem. I will try do some investigating.

**Comment by Morb1us** [comment] 2018-01-19 16:38
I tried with different desktop compositions, font size and no result

**Comment by ITOpsMgr** [comment] 2018-02-12 13:52
Hi, ive just come across this tool and I have the same issue in that there is no import button, ive tried the previous release and have the same problem.

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.16299 N/A Build 16299

**Comment by damienhaynes** [comment] 2018-02-12 22:09
I don't quite yet understand why it works on some desktops and not others. 

I have tested on Win7 with 100% DPI and Win10 with 150% and looks correct.

**Comment by Eatkoolaid** [comment] 2018-02-21 05:46
Windows 10 here. Same problem. (1366x768)

**Comment by damienhaynes** [comment] 2018-02-21 05:49
I wonder if its a problem with the resolution, can you try another machine that has a higher resolution screen e.g. 1920x1080 or more.

**Comment by Morb1us** [comment] 2018-03-10 16:36
I connected the PC to the TV (1920x1080) and everything is ok.

**Comment by guindous** [comment] 2018-03-14 22:18
Same here. Windows 10. (1366x768).

**Comment by damienhaynes** [comment] 2018-03-14 22:26
Good to know, at least now I have something to work with.

**Comment by guindous** [comment] 2018-03-14 22:28
@damienhaynes If you give me some hints to provide you a log, i will gladly.

**Comment by damienhaynes** [comment] 2018-03-14 22:33
No thats okay, it seems the issue is due to the resolution. If you change it to 1920x1080 you will be okay.

I should be able to fix this issue by making the dialog scale and scroll as appropriate for smaller screens.

**Comment by guindous** [comment] 2018-03-14 23:19
My laptop monitor doesn't support that resolution. Hope will be solved next version. Thanks for your fast response.

**Comment by damienhaynes** [comment] 2018-04-13 23:30
This should hopefully be fixed now, I have re-worked the dialog to be re-sizeable.

Can you please try the attached exe and see report back if fixed.

**Comment by guindous** [comment] 2018-04-14 14:33
Worked great! Thanks! 👍

**Comment by damienhaynes** [comment] 2018-04-14 22:38
Awesome, thanks for the feedback.

**Closed** 2018-04-14 23:00 UTC
