### ISSUE TITLE
Import CSV to lists other than the watchlist

### ISSUE THREAD

**Issue by dairefagan** [damienhaynes/TraktRater#46] opened 2016-03-16 15:44 UTC
Hi

I first uploaded my IMDB TV Shows and Movies lists individually before in turn manually assigning each item to my TV Shows or Movies list. I like to keep a watch list, but also a separate TV Show and Movies lists.

it seems trakt-tv-list-importer used to do this but there is some issue with it logging in, which I am guessing is due to a change Trakt made since the program was last updated. It does not look like it is going to be updated as it is still on Google Code.

I think I read somewhere there were plans for TraktRater to upload to different lists - can you please implement this? I would like to import some large movie lists, but I do not think I can handle sitting in front of the computer for hours manually assigning them! :) 

- Perhaps you would also consider an option to overwrite or merge to the existing list, although I guess this can be achieved using the maintenance options.

**Comment by dairefagan** [comment] 2016-03-22 15:05
Is this something you can consider please?

**Comment by damienhaynes** [comment] 2016-03-22 22:39
Hi,

So are you asking for IMDb List Import? I do have plans to add this when I find the time.

**Comment by dairefagan** [comment] 2016-03-22 23:34
Hi

Firstly, thanks for coding this, it did help me!

Well, yes, although as you know better than I do, we can already import
IMDB lists. The issue I have with this is that they can only be imported to
the watchlist, and if one wants to keep a separate list which will not have
items removed as watched, like say I do with TV Shows for Kodi purposes,
they have to, or at least I did, manually move 300 shows from the watchlist
to TV Show list.

It would be great if I could have just imported the shows directly to a TV
Show list. An option to merge or overwrite would be a bonus, though I think
merging is already the default option, and we can just use the maintenance
option, in in program or on site, to delete lists first if we want to
overwrite?

Please let me know if I can help.

Thanks

Dáire.

**Comment by damienhaynes** [comment] 2016-03-22 23:36
Yeah, the plan is to map an IMDb list to a custom Trakt list. As you already say there is a way to import to Watchlist already so I definitely want to distinguish between the two.

I also think having the options to _delete and import _or _add only_ is a good addition.

**Comment by dairefagan** [comment] 2016-03-22 23:45
If you are not planning to already, can you please make it so it's not just
IMDB lists that can be imported to a custom list, but other lists also so
users are not constrained?

**Comment by dairefagan** [comment] 2016-03-22 23:47
I wonder could you use any of the code from that program that used to do it?

How about exporting from our lists on Trakt? I think they specify users
must have a paid account to do this from the website.

**Comment by damienhaynes** [comment] 2016-03-22 23:50
I will see what I can do about making a generic importer.

An Export feature would be a nice thing to add in the future as well. I never realised that was a VIP feature.

**Comment by CarsonGallo** [comment] 2016-03-22 23:52
SideReel import would be extremely helpful for me. I've put in 2 hours worth of work of manually copying over all the shows and show episodes I've wateched, and I'm maybe only a third of tge way done.

**Comment by damienhaynes** [comment] 2016-03-22 23:53
I have plans to add CSV import from Letterboxed, if you want SideReel Import as well may I suggest opening a new ticket with a sample file if you have one handy.

**Comment by dairefagan** [comment] 2016-03-23 00:11
IMDB and/or CSV would be a great start! :)

Yes, I think I read CSV export is premium only feature, though I am sure
you will confirm this yourself before coding anything. As a premium
feature, is there anyway doing it with the API would not be possible as how
they have set it up?

**Comment by damienhaynes** [comment] 2016-03-23 00:14
The API has unrestricted access to a users data currently, so its possible to do this without VIP membership.

**Comment by damienhaynes** [comment] 2016-04-05 20:50
This is basically a duplicate of Issue #25.

I have now added support to import IMDb CSV custom lists to trakt. It currently supports Shows and Movies.

Additional features in this issue should be added as seperate tasks to the issue tracker.

**Closed by damienhaynes** 2016-04-05 20:50 UTC

**Comment by dairefagan** [comment] 2016-05-02 14:52
Damien

I want to download some csv files from IMDB, like say top 250 movies, and
import them to my Trakt custom list Movies.

I have downloaded version 2.2.1.1 and I see the option for custom lists. If
I want these csv files to merge with my custom list Movies, do I just name
the file Movies.csv. Checking with you first as I do not want to overwrite
my watched list, or Movies or TV Shows list.

Please let me know.

Thanks

**Comment by damienhaynes** [comment] 2016-05-02 23:15
Correct, it just uses the name of the CSV file for the Custom List name.

**Comment by dairefagan** [comment] 2016-05-04 14:54
I found various pieces of software that would scrape the top 250 from IMDB,
as there is no export option for that particular list, but none of them are
in date or create a CSV. Instead I manually added each movie from the top
250 list ot my own list Movies, which I then exported to my computer.

Then in TraktRater I generated a token, input it to TraktRater, and then in
the IMDB tab checked enabled, selected CSV import, and under custom lists I
selected the  file Movies.csv. My intetion was to merge this with my Trakt
list Movies, but instead TraktRater output the error:

IMDB: object reference not set to an instance of an object

Please find the log attached and advise.

**Comment by dairefagan** [comment] 2016-05-04 17:22
I cannot get the attached list to import fully, no matter how many times I
try. I started out with no custom list matching the name, and let
TraktRater create it, but it should import 643 movies, and instead will
only import 489?

**Comment by damienhaynes** [comment] 2016-05-05 03:24
HI dairefagan, you haven't attached anything for me to check?

**Comment by dairefagan** [comment] 2016-05-06 13:58
I attached to the mail, but Github either does not support that and I have to post using Github itself as I am now, or it did not upload because of the file extension. Please find the zip attached to this:
[moviesnew2.csv.zip](https://github.com/damienhaynes/TraktRater/files/252349/moviesnew2.csv.zip)

**Comment by dairefagan** [comment] 2016-05-06 14:10
Looking at this again, the list I am trying to upload is a merge of top 250, top 100 thrillers, top sci-fi, and something else - I think duplicates may accounts for the discrepency in the number of movies in the Trakt list.

That said, if I change the name to Movies (which is the name of an existing list I keep on Trakt), I am still receiving the error: IMDB: object reference not set to an instance of an object.

Can you please try to reproduce?

**Comment by dairefagan** [comment] 2016-05-06 14:29
I removed duplicates, and there are still 562 individual entries, but Trakt only has a list of 489. Here is the updated file:
[moviesnew2.zip](https://github.com/damienhaynes/TraktRater/files/252417/moviesnew2.zip)

**Comment by dairefagan** [comment] 2016-05-06 14:33
I tried again changing the name to Movies.csv, and TraktRater just overwrote my custom Movie list :( It is now displaying just 1 Movie for some reason.

**Comment by dairefagan** [comment] 2016-05-06 14:42
I tried merging an old personal IMDB list I kept, with the movies2new, removed duplicaes using excel filter, I changed the name to Movies.csv, and I deleted my existing Movies list on Trakt. There are 881 unique movies in this csv file, and I watched Trakt cycle through the 18 pages, but still the newly created list is 489 - this seems to be some kind of limit?

**Comment by damienhaynes** [comment] 2016-05-07 11:52
Can we just try to deal with one problem at a time, the last csv you gave me had 562 entries with duplicates. 

I dont know if there is limits, I would have to see your log file of the import. 

Please give me the CSV which you think contains 881 unique entries, lets deal with that first. the last comment does not point to this file.
