### ISSUE TITLE
Help: TraktRater on Mac

### ISSUE THREAD

**Issue by ivoce** [damienhaynes/TraktRater#72] opened 2017-11-23 18:25 UTC
Hi there! I'm having trouble getting TraktRater installed and functioning on my new MacBook.. Is there anyone who can help me out? Thanks in advance! Kind regards x

**Comment by dzg** [comment] 2017-12-09 18:42
Anyone? Do you run the exe with mono?

**Comment by damienhaynes** [comment] 2017-12-09 21:44
Its been a while since I tried since I primarily use Windows. I will try find some time to get mono environment up and running again and see if there is any compatibility issues since last supported.

**Comment by damienhaynes** [comment] 2018-01-05 01:33
Closing this off as its a duplicate of #73

**Closed by damienhaynes** 2018-01-05 01:33 UTC
